// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfuldixplwtnbmcnybph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdWxkaXhwbHd0bmJtY255YnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODk5OTAsImV4cCI6MjA2NTQ2NTk5MH0.RqEhHFFVfL_TKxHFpM827KeX0xYvwNxu6GLeEfcruoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);